/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VersesIndexRouteImport } from './routes/verses/index'
import { Route as VersesNewRouteImport } from './routes/verses/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VersesIndexRoute = VersesIndexRouteImport.update({
  id: '/verses/',
  path: '/verses/',
  getParentRoute: () => rootRouteImport,
} as any)
const VersesNewRoute = VersesNewRouteImport.update({
  id: '/verses/new',
  path: '/verses/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/verses/new': typeof VersesNewRoute
  '/verses/': typeof VersesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/verses/new': typeof VersesNewRoute
  '/verses': typeof VersesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/verses/new': typeof VersesNewRoute
  '/verses/': typeof VersesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/verses/new' | '/verses/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/verses/new' | '/verses'
  id: '__root__' | '/' | '/verses/new' | '/verses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VersesNewRoute: typeof VersesNewRoute
  VersesIndexRoute: typeof VersesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verses/': {
      id: '/verses/'
      path: '/verses'
      fullPath: '/verses/'
      preLoaderRoute: typeof VersesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verses/new': {
      id: '/verses/new'
      path: '/verses/new'
      fullPath: '/verses/new'
      preLoaderRoute: typeof VersesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VersesNewRoute: VersesNewRoute,
  VersesIndexRoute: VersesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
