/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VersesIndexRouteImport } from './routes/verses/index'
import { Route as VersesNewRouteImport } from './routes/verses/new'
import { Route as SettingsLanguageRouteImport } from './routes/settings/language'

const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VersesIndexRoute = VersesIndexRouteImport.update({
  id: '/verses/',
  path: '/verses/',
  getParentRoute: () => rootRouteImport,
} as any)
const VersesNewRoute = VersesNewRouteImport.update({
  id: '/verses/new',
  path: '/verses/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsLanguageRoute = SettingsLanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => SettingsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/settings/language': typeof SettingsLanguageRoute
  '/verses/new': typeof VersesNewRoute
  '/verses/': typeof VersesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/settings/language': typeof SettingsLanguageRoute
  '/verses/new': typeof VersesNewRoute
  '/verses': typeof VersesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/settings/language': typeof SettingsLanguageRoute
  '/verses/new': typeof VersesNewRoute
  '/verses/': typeof VersesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/settings' | '/settings/language' | '/verses/new' | '/verses/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings' | '/settings/language' | '/verses/new' | '/verses'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/settings/language'
    | '/verses/new'
    | '/verses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  VersesNewRoute: typeof VersesNewRoute
  VersesIndexRoute: typeof VersesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verses/': {
      id: '/verses/'
      path: '/verses'
      fullPath: '/verses/'
      preLoaderRoute: typeof VersesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verses/new': {
      id: '/verses/new'
      path: '/verses/new'
      fullPath: '/verses/new'
      preLoaderRoute: typeof VersesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/language': {
      id: '/settings/language'
      path: '/language'
      fullPath: '/settings/language'
      preLoaderRoute: typeof SettingsLanguageRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
  }
}

interface SettingsRouteRouteChildren {
  SettingsLanguageRoute: typeof SettingsLanguageRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsLanguageRoute: SettingsLanguageRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  VersesNewRoute: VersesNewRoute,
  VersesIndexRoute: VersesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
